### PR TITLE
Loosens Contexts

### LINKED ISSUE #2: Loosen Contexts
Fix the context types to match the changes made in the interfaces package [here](https://github.com/Dhii/output-renderer-interface/pull/15).

### PR DESCRIPTION
**Pull request by mecha**
Fixes #2

### CODE REVIEW

**Comment by XedinUnknown** [comment]
@mecha, changelog.

**Comment by mecha** [comment]
@XedinUnknown There is nothing to add, since there hasn't been a release yet.

**Comment by mecha** [comment]
@XedinUnknown Be advised, there is an unreleased relevant dependency: [`dhii/output-renderer-abstract`](https://github.com/dhii/output-renderer-abstract).

**Comment by XedinUnknown** [comment]
😮 A dependency of what, @mecha?

**Comment by mecha** [comment]
Of this package ...

**Comment by XedinUnknown** [comment]
Show me the line in [`composer.json`](https://github.com/Dhii/output-renderer-base/blob/fix/2-loosen-contexts/composer.json).

**Comment by mecha** [comment]
My bad. I meant [`dhii/output-renderer-abstract`](https://github.com/dhii/output-renderer-abstract).

**Pull request merged**
